### ISSUE TITLE
No Patch Address Found for either hook for Instagram v43

### ISSUE THREAD

**Issue by zweed4u** [karek314/hexbytescanner-hooks#1]
Extracted thin arm64, was unable to find address with either pattern.
Let me know how/if I can contribute and find viable SSL patterns in Hopper.

**Comment by karek314** [comment]
It looks like this job needs to be done again, mentioned binary have OpenSSL 1.1.0. While hooks in this one work for 1.0.2.

I will take a look as soon i can.

**Comment by karek314** [comment]
for 1.1.0  - this is what needs to be replaced with no operation op code. https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/ssl/statem/statem_clnt.c#L1212

**Comment by karek314** [comment]
Slightly different, more in readme.
https://github.com/karek314/hexbytescanner-hooks/commit/00bccbf75a8330295cc5a517083a1a247af16c93

**Comment by hitrain** [comment]
not worked v56
