### ISSUE TITLE
Instagram v70.1 .

### ISSUE THREAD

**Issue by gaplan** [karek314/hexbytescanner-hooks#4]
Hello There.
i'm trying patch for 70.1
./hexbytescanner openssl_1_1_0_hook.json /HandyIPAPatcher/Instagram_arm64 

HexByteScanner by karek314
Json mode
File:/HandyIPAPatcher/Instagram_arm64
Config:openssl_1_1_0_hook.json
Task count: 1
Patch Task pattern FFB5E00313AAE103??AA??????????0300 with patch bytes 02 at distance 0x3
Searching with pattern: ff b5 e0 03 13 aa e1 03 ?? aa ?? ?? ?? ?? ?? 03 00
Data Lenght 55623504
Starting scanner
Progress: 13.14%
Found matching pattern at 0x1c896be -> ff b5 e0 03 13 aa e1 03 14 aa 2d e3 ff 97 f5 03 00
Progress: 93.91%
Progress: 100.00
Found locations:(
    0x1c896be
)
Scanning took:235.78s
Patching:0x1c896be
Patching with bytes: 02
Data Lenght 55623504
[0x1c896c1]Current opcode: 06
[0x1c896c1]Replaced opcode: 02
Done.
/HandyIPAPatcher/Instagram_arm64_patched saved.

And 
bash replace_bin.sh fat trim 
But,  
still getting ssl error

**Comment by karek314** [comment]
Hi, perhaps mentioned application is no longer relying on OpenSSL with certificate pinning. If you find new hook, you can make PR to this repo, thus i will leave issue open for time being.

**Comment by gaplan** [comment]
i'm really sorry, my bad. 
i'm using this.

[
  {
    "pattern": "FFB5E00313AAE103??AA??????????0300",
    "patchBytes": "02",
    "patchDistance": "0x3"
  }
]

this code Found matching pattern at 0x1c896be

**Comment by gaplan** [comment]
i can do that. Thank you.

**Comment by gaplan** [comment]
I'm really sory abot that. 
my mistake. I can do that. thank you so much.

**Comment by karek314** [comment]
No problem, so it worked ?

**Comment by gaplan** [comment]
it is working. Thank you so much. 
if i try with Iphone 4.1 does not working. But if i try iphone6x working without errors.
thanks again.

**Comment by karek314** [comment]
Perhaps you patched wrong architecture and that's why it didn't worked. If I recall correctly, iPhone 4.1 is arm7. This patch is arm64 ONLY.

**Comment by gaplan** [comment]
yes you're right.
