### ISSUE TITLE
OpenSSL 1.1.1

### ISSUE THREAD

**Issue by nikolaflock** [karek314/hexbytescanner-hooks#6]
Any chance of getting the updated version for OpenSSL 1.1.1 or pointing me in the good direction on how to do it myself?

Thanks

**Comment by karek314** [comment]
Hey,
I don't have time for this now, you should look at tls_process_server_certificate method, or something similarly related to certificate handshake, you can look up in open source code and then find it in binary, if you are lucky and symbols are included then it should be easy.
